### ISSUE TITLE
Not all data present in excel

### ISSUE THREAD

**Issue by BrandonCline85** [microsoft/ARI#206]
When running versions 3.1.13 and 3.1.38, I'm noticing discrepancies in the output for resources, with some resources not displaying the correct amounts. Is there a workaround for this, or is it a new issue?
![ARI 8-13-24](https://github.com/user-attachments/assets/d7aa1ecd-55c7-4c15-bb06-820685eb28c5)

**Comment by Claudio-Merola** [comment]
Hello @BrandonCline85 

Looks like something that should be fixed already.

Can you run the version 3.1.38 with -Debug and see how many Jobs run at the same time during the "Processing Inventory" ?

**Comment by BrandonCline85** [comment]
Yes, I can run that and paste the output here. It might be tomorrow before I can get to it though.

**Comment by BrandonCline85** [comment]
![image](https://github.com/user-attachments/assets/746be8a3-176a-434e-b45f-0c5ce101fe7a)

**Comment by BrandonCline85** [comment]
PS C:\Scripts-Utilities\Powershell\ARI-main-3.1.38\ARI-main> .\AzureResourceInventory.ps1 -tenantid [redacted] -debug                                                                                                 DEBUG: 2024-08-19_08_04_36 - Debbuging Mode: On. ErrorActionPreference was set to "Continue", every error will be       presented.                                                                                                              DEBUG: 2024-08-19_08_04_36 - Cleaning default variables                                                                 DEBUG: 2024-08-19_08_04_36 - Checking if -Online parameter will have to be forced.                                      DEBUG: 2024-08-19_08_04_36 - Starting Extractor function                                                                DEBUG: 2024-08-19_08_04_36 - Powershell Edition: Desktop                                                                DEBUG: 2024-08-19_08_04_36 - Powershell Version: 5.1.19041.4648                                                         DEBUG: 2024-08-19_08_04_36 - Starting checkAzCli function                                                               Validating Az Cli..                                                                                                     DEBUG: 2024-08-19_08_04_38 - Current az cli version: azure-cli                         2.63.0                           Validating Az Cli Extension..                                                                                           DEBUG: 2024-08-19_08_04_38 - Current Resource-Graph Extension Version: 2.1.0                                            Validating ImportExcel Module..                                                                                         DEBUG: 2024-08-19_08_04_40 - ImportExcel Module Version: 7.8.9                                                          DEBUG: 2024-08-19_08_04_41 - Starting checkPS function                                                                  PowerShell Desktop Identified.                                                                                                                                                                                                                  DEBUG: 2024-08-19_08_04_41 - Starting LoginSession function                                                             Azure Cloud Environment: AzureCloud                                                                                     ERROR: Configuration 'core.enable_broker_on_windows' is not set.                                                        DEBUG: 2024-08-19_08_05_04 - Tags will be ignored                                                                       DEBUG: 2024-08-19_08_05_04 - Number of Subscriptions Found: 7                                                           DEBUG: 2024-08-19_08_05_04 - Checking report folder: C:\AzureResourceInventory\                                         DEBUG: 2024-08-19_08_05_04 - Invoking Inventory Loop for Resources                                                      DEBUG: 2024-08-19_08_05_07 - Invoking Inventory Loop for Network Resources                                              DEBUG: 2024-08-19_08_05_09 - Invoking Inventory Loop for Backup Resources                                               DEBUG: 2024-08-19_08_05_11 - Invoking Inventory Loop for AVD Resources                                                  DEBUG: 2024-08-19_08_05_13 - Invoking Inventory Loop for Resource Containers                                            DEBUG: 2024-08-19_08_05_16 - Invoking Inventory Loop for Policies Resources                                             DEBUG: 2024-08-19_08_05_18 - Invoking Inventory Loop for Advisories                                                     DEBUG: 2024-08-19_08_05_21 - Excel file:C:\AzureResourceInventory\AzureResourceInventory_Report_2024-08-19_08_05.xlsx   DEBUG: 2024-08-19_08_05_21 - Excel Table Style used: Light19                                                            DEBUG: 2024-08-19_08_05_21 - Importing List of Unsupported Versions.                                                    DEBUG: 2024-08-19_08_05_21 - Looking for the following file:                                                            C:\Scripts-Utilities\Powershell\ARI-main-3.1.38\ARI-main\Extras\Support.json                                            DEBUG: 2024-08-19_08_05_21 - Checking if Draw.io Diagram Job Should be Run.                                             DEBUG: 2024-08-19_08_05_21 - Starting Draw.io Diagram Processing Job.                                                   DEBUG: 2024-08-19_08_05_21 - Checking If Should Run Security Center Job.                                                DEBUG: 2024-08-19_08_05_21 - Checking If Should Run Policy Job.                                                         DEBUG: 2024-08-19_08_05_21 - Starting Policy Processing Job.                                                            DEBUG: 2024-08-19_08_05_21 - Checking If Should Run Advisory Job.                                                       DEBUG: 2024-08-19_08_05_21 - Starting Advisory Processing Job.                                                          DEBUG: 2024-08-19_08_05_21 - Starting Subscriptions job.                                                                DEBUG: 2024-08-19_08_05_22 - Starting Processing Jobs in Small Mode.                                                    DEBUG: 2024-08-19_08_05_22 - Total Resources Being Processed: 535                                                       DEBUG: 2024-08-19_08_05_22 - Resources Being Processed in ResourceJob_1: 535                                            DEBUG: 2024-08-19_08_05_22 - Starting Jobs Collector.                                                                   DEBUG: 2024-08-19_08_05_22 - Jobs Still Running: 1                                                                      DEBUG: 2024-08-19_08_05_27 - Jobs Still Running: 1                                                                      DEBUG: 2024-08-19_08_05_32 - Jobs Still Running: 1                                                                      DEBUG: 2024-08-19_08_05_37 - Jobs Still Running: 1                                                                      DEBUG: 2024-08-19_08_05_42 - Jobs Still Running: 1                                                                      DEBUG: 2024-08-19_08_05_47 - Jobs Still Running: 1                                                                      DEBUG: 2024-08-19_08_05_52 - Jobs Still Running: 1                                                                      DEBUG: 2024-08-19_08_05_57 - Jobs Still Running: 1                                                                      DEBUG: 2024-08-19_08_06_02 - Jobs Still Running: 1                                                                      DEBUG: 2024-08-19_08_06_07 - Jobs Still Running: 1                                                                      DEBUG: 2024-08-19_08_06_13 - Jobs Still Running: 1                                                                      DEBUG: 2024-08-19_08_06_18 - Jobs Still Running: 1                                                                      DEBUG: 2024-08-19_08_06_23 - Jobs Still Running: 1                                                                      DEBUG: 2024-08-19_08_06_28 - Jobs Still Running: 1                                                                      DEBUG: 2024-08-19_08_06_33 - Jobs Still Running: 1                                                                      DEBUG: 2024-08-19_08_06_38 - Jobs Still Running: 1                                                                      DEBUG: 2024-08-19_08_06_43 - Jobs Still Running: 1                                                                      DEBUG: 2024-08-19_08_06_48 - Jobs Still Running: 1                                                                      DEBUG: 2024-08-19_08_06_53 - Jobs Still Running: 1                                                                      DEBUG: 2024-08-19_08_06_58 - Jobs Still Running: 1                                                                      DEBUG: 2024-08-19_08_07_03 - Jobs Still Running: 1                                                                      DEBUG: 2024-08-19_08_07_08 - Jobs Still Running: 1                                                                      DEBUG: 2024-08-19_08_07_13 - Jobs Still Running: 1                                                                      DEBUG: 2024-08-19_08_07_18 - Jobs Compleated.                                                                           DEBUG: 2024-08-19_08_07_18 - Job ResourceJob_1 Returned: 30 Resource Types.                                             DEBUG: 2024-08-19_08_07_18 - Starting Reporting Phase.                                                                  DEBUG: 2024-08-19_08_07_18 - Running Offline, Gathering List Of Modules.                                                DEBUG: 2024-08-19_08_07_18 - Modules Found: 78                                                                          DEBUG: 2024-08-19_08_07_18 - Running Module: 'Databricks'. Resources Count: 4                                           DEBUG: 2024-08-19_08_07_22 - Running Module: 'WrkSpace'. Resources Count: 10                                            DEBUG: 2024-08-19_08_07_23 - Running Module: 'AVD'. Resources Count: 2                                                  DEBUG: 2024-08-19_08_07_24 - Running Module: 'VM'. Resources Count: 43                                                  DEBUG: 2024-08-19_08_07_25 - Running Module: 'RedisCache'. Resources Count: 26                                          DEBUG: 2024-08-19_08_07_26 - Running Module: 'SQLDB'. Resources Count: 9                                                DEBUG: 2024-08-19_08_07_27 - Running Module: 'SQLSERVER'. Resources Count: 6                                            DEBUG: 2024-08-19_08_07_27 - Running Module: 'SQLVM'. Resources Count: 13
DEBUG: 2024-08-19_08_07_28 - Running Module: 'AutomationAcc'. Resources Count: 2
DEBUG: 2024-08-19_08_07_29 - Running Module: 'BASTION'. Resources Count: 12
DEBUG: 2024-08-19_08_07_29 - Running Module: 'RecoveryVault'. Resources Count: 2
DEBUG: 2024-08-19_08_07_30 - Running Module: 'Vault'. Resources Count: 56
DEBUG: 2024-08-19_08_07_31 - Running Module: 'Backup'. Resources Count: 9
DEBUG: 2024-08-19_08_07_32 - Running Module: 'ServiceBUS'. Resources Count: 2
DEBUG: 2024-08-19_08_07_32 - Running Module: 'AzureFirewall'. Resources Count: 20
DEBUG: 2024-08-19_08_07_33 - Running Module: 'Connections'. Resources Count: 3
DEBUG: 2024-08-19_08_07_34 - Running Module: 'LoadBalancer'. Resources Count: 13
DEBUG: 2024-08-19_08_07_35 - Running Module: 'NATGAteway'. Resources Count: 4
DEBUG: 2024-08-19_08_07_35 - Running Module: 'NetworkInterface'. Resources Count: 50
DEBUG: 2024-08-19_08_07_36 - Running Module: 'NetworkSecurityGroup'. Resources Count: 63
DEBUG: 2024-08-19_08_07_37 - Running Module: 'PrivateDNS'. Resources Count: 9
DEBUG: 2024-08-19_08_07_37 - Running Module: 'PrivateEndpoint'. Resources Count: 5
DEBUG: 2024-08-19_08_07_38 - Running Module: 'PublicDNS'. Resources Count: 4
DEBUG: 2024-08-19_08_07_39 - Running Module: 'PublicIP'. Resources Count: 12
DEBUG: 2024-08-19_08_07_39 - Running Module: 'ROUTETABLE'. Resources Count: 48
DEBUG: 2024-08-19_08_07_40 - Running Module: 'VirtualNetwork'. Resources Count: 32
DEBUG: 2024-08-19_08_07_41 - Running Module: 'VNETGTW'. Resources Count: 20
DEBUG: 2024-08-19_08_07_42 - Running Module: 'vNETPeering'. Resources Count: 21
DEBUG: 2024-08-19_08_07_43 - Running Module: 'StorageAcc'. Resources Count: 26
DEBUG: 2024-08-19_08_07_44 - Running Module: 'VMDisk'. Resources Count: 78
DEBUG: 2024-08-19_08_07_44 - Resource Reporting Phase Done.
DEBUG: 2024-08-19_08_07_44 - Checking if Should Generate Security Center Sheet.
DEBUG: 2024-08-19_08_07_44 - Checking if Should Generate Policy Sheet.
DEBUG: 2024-08-19_08_07_44 - Generating Policy Sheet.
DEBUG: 2024-08-19_08_07_45 - Looking for the following file:
C:\Scripts-Utilities\Powershell\ARI-main-3.1.38\ARI-main\Extras\Policy.ps1
DEBUG: 2024-08-19_08_07_45 - Checking if Should Generate Advisory Sheet.
DEBUG: 2024-08-19_08_07_45 - Generating Advisor Sheet.
DEBUG: 2024-08-19_08_07_45 - Looking for the following file:
C:\Scripts-Utilities\Powershell\ARI-main-3.1.38\ARI-main\Extras\Advisory.ps1
DEBUG: 2024-08-19_08_07_46 - Generating Subscription sheet for: 7 Subscriptions.
DEBUG: 2024-08-19_08_07_46 - Looking for the following file:
C:\Scripts-Utilities\Powershell\ARI-main-3.1.38\ARI-main\Extras\Subscriptions.ps1
DEBUG: 2024-08-19_08_07_47 - Generating Overview sheet (Charts).
DEBUG: 2024-08-19_08_07_47 - Looking for the following file:
C:\Scripts-Utilities\Powershell\ARI-main-3.1.38\ARI-main\Extras\Charts.ps1
DEBUG: 2024-08-19_08_07_54 - Finished Charts Phase.
Report Complete. Total Runtime was: 3.3 Minutes
Total Resources: 535
Total Advisories: 870
Total Policies: 38

**Comment by BrandonCline85** [comment]
The individual tabs are showing the amount that is listed in the overview, and that number is what is different than what is in the azure portal.

**Comment by BrandonCline85** [comment]
On the NSG's it is showing 13 on the overview, 63 in the tab and the azure portal only has 24

**Comment by BrandonCline85** [comment]
Key vaults it shows 10 in the overview, 56 in the tab and there are 13 in the azure portal

**Comment by Claudio-Merola** [comment]
@BrandonCline85 

Yes, because the script will add one line for each "Access Policy" in the Key Vault tab and for NSG it will add one line for each "Security Rule". But the number of unique resources in these tabs are 13 or 24 (for the NSG) and 10 or 13 (for the key vaults)?

**Comment by BrandonCline85** [comment]
Correct.

**Comment by Claudio-Merola** [comment]
Hello, I just released the version 3.5. and since we changed a lot of how the script works (it's no longer a script, but a Powershell Module) and we completely remove the need of az cli as we changed 100% to powershell. This might have changed the previous behavior.

Do you mind and give a try to new version so we can validate if this issue is fixed?

Thanks

**Comment by BrandonCline85** [comment]
Thanks for the update. I’m off work today but I will check tomorrow and let you know.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by BrandonCline85** [comment]
Key Vaults is still showing only 10 items in the spreadsheet and there are 13 currently being used. Azure Firewall is only displaying 1 firewall in the spreadsheet, when there are 2 in place. Please let me know if you need any further info from me. Thanks.

**Comment by Claudio-Merola** [comment]
@BrandonCline85 , does the missing Key Vaults have Access Policies configured?

@dersteppenwolf, that is just in the Overview or the PostgreeSQL Flexible sheet is also empty?

**Comment by dersteppenwolf** [comment]
> in the Overview or the PostgreeSQL Flexible sheet is also empty?

Both

**Comment by BrandonCline85** [comment]
@Claudio-Merola yes there are access policies configured on 10 of them. I'm guessing that is why the other 3 didn't show up in the report.

**Comment by Claudio-Merola** [comment]
@BrandonCline85 , got it. It should be fixed in the next version (3.5.1). We intend to release it next week.

@dersteppenwolf 

Can you check if the resource type of the PostgreeSQL Flexible you have in your environment is: "Microsoft.DBforPostgreSQL/flexibleServers"?

You can check that in the "JSON View" of any your resources.

**Comment by dersteppenwolf** [comment]
> Can you check if the resource type of the PostgreeSQL Flexible you have in your environment is: "Microsoft.DBforPostgreSQL/flexibleServers"?
> 
> You can check that in the "JSON View" of any your resources.
Looks like this: 
//Microsoft.DBforPostgreSQL/flexibleServers/

**Comment by Claudio-Merola** [comment]
@dersteppenwolf 

That is strange. Can you run the script adding the "-Debug" parameter and post the output here?

**Comment by Claudio-Merola** [comment]
@dersteppenwolf 

That is odd.

"Running Module: 'POSTGREFlexible'. Lines Count: 7"

This indicate the Postgree Flexible itself was processed correctly and 7 lines should have been added to the Excel file.

The PostgreeSQL Flexible sheet is totally blank and no resources are present? or it has the column titles and there is no resources?

**Comment by dersteppenwolf** [comment]
> The PostgreeSQL Flexible sheet is totally blank and no resources are present? or it has the column titles and there is no resources?

The sheet es totally blank.

**Comment by Claudio-Merola** [comment]
Hey @dersteppenwolf 

I just published the version 3.5.1 of the module and this issue should be fixed. Can you try to upgrade your version of the module and try again?

Thanks

**Comment by dersteppenwolf** [comment]
> Hey @dersteppenwolf
> 
> I just published the version 3.5.1 of the module and this issue should be fixed. Can you try to upgrade your version of the module and try again?
> 
> Thanks

The command takes too much time and doesn't finish.

**Comment by dersteppenwolf** [comment]
The sheet is again  totally blank.

**Version:**

Get-InstalledModule  -Name AzureResourceInventory
Version    Name                                Repository           Description
-------    ----                                ----------           -----------
3.5.7      AzureResourceInventory              PSGallery


**Command:**

Invoke-ARI  -TenantID xxx  -DiagramFullEnvironment -ReportDir “C:\tmp\AzureResourceInventory\”  -QuotaUsage  -SecurityCenter  -Debug


**Log:**

DEPURACIÓN: 2024-10-16_20_40_19 - Running Module: 'POSTGREFlexible'. Lines Count: 7
