### ISSUE TITLE
Automation Account Script receiving 404 for URL in $Script:RawRepo

### ISSUE THREAD

**Issue by weekendclimber** [microsoft/ARI#216]
Version: 3.1.9

See the error message below. The value of the variable is: 'https://raw.githubusercontent.com/microsoft/ARI/main'

Receiving a 404 even trying to access from a browser or other methods.

![image](https://github.com/user-attachments/assets/4c71b855-7b8a-4b5d-a9c3-7a5742ceabab)

**Comment by Claudio-Merola** [comment]
@weekendclimber 

We released a new version of the script, now as a Powershell Module.

Can you try this version?

**Comment by weekendclimber** [comment]
I will give it a go tomorrow and report back.

**Comment by weekendclimber** [comment]
That is still throwing some errors and the output does not get generated. Here is my command in the runbook:
 
![image](https://github.com/user-attachments/assets/9153ba00-e2d2-40bf-b69c-3a2ba6b1a60d)

Here is the error output:

```
9/13/2024, 3:42:49 PM - Warning: TenantId 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' contains more than one active subscription. First one will be selected for further use. To select another subscription, use Set-AzContext.
9/13/2024, 3:42:49 PM - Warning: To override which subscription Connect-AzAccount selects by default, use `Update-AzConfig -DefaultSubscriptionForLogin 00000000-0000-0000-0000-000000000000`. Go to https://go.microsoft.com/fwlink/?linkid=2200610 for more information.
9/13/2024, 3:47:28 PM - Error: 
OperationStopped: 
Line |
  28 |      $DataBricks = $Resources | Where-Object { $_.TYPE -eq 'microsoft. …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception of type 'System.OutOfMemoryException' was thrown.

9/13/2024, 3:47:30 PM - Error: 
OperationStopped: 
Line |
  31 |      $DocIntelligence = $Resources | Where-Object {$_.TYPE -eq 'micros …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception of type 'System.OutOfMemoryException' was thrown.

9/13/2024, 3:47:35 PM - Error: 

9/13/2024, 3:50:29 PM - Error: 
```

**Comment by Claudio-Merola** [comment]
@weekendclimber 

"Exception of type 'System.OutOfMemoryException' was thrown"

That happens due to the computer power in the regular Automation Account being too small for that environment. 

Use "Hybrid Runbook Workers" with more memory and computing power to run the Runbook. (https://learn.microsoft.com/en-us/azure/automation/automation-hybrid-runbook-worker)
